"""
sqlfy.dialects
==============
Dialect adapters for multi-database support.

Provides type normalization and dialect-specific behavior for:
- Oracle (default)
- PostgreSQL
- MySQL
- SQLite

Type Normalization Strategy
---------------------------
Normalizes dialect-specific types to canonical forms:
- VARCHAR2/TEXT → VARCHAR
- NUMBER/NUMERIC → NUMERIC
- SERIAL/AUTO_INCREMENT → INTEGER (with auto_increment flag)
- DATETIME/TIMESTAMPTZ → TIMESTAMP

Auto-increment Detection
------------------------
Each dialect has different syntax for auto-increment columns:
- Oracle: GENERATED BY DEFAULT AS IDENTITY
- Postgres: SERIAL, BIGSERIAL, or GENERATED ALWAYS AS IDENTITY
- MySQL: AUTO_INCREMENT
- SQLite: INTEGER PRIMARY KEY AUTOINCREMENT

Usage
-----
    adapter = DialectAdapter.for_dialect('postgres')
    normalized = adapter.normalize_type('SERIAL')  # Returns 'INTEGER'
    is_auto = adapter.is_auto_increment('SERIAL PRIMARY KEY')  # Returns True
"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from typing import ClassVar


class DialectAdapter(ABC):
    """Base class for dialect-specific behavior."""
    
    name: str
    
    # Type normalization map: dialect_type → canonical_type
    type_map: ClassVar[dict[str, str]] = {}
    
    @abstractmethod
    def normalize_type(self, type_str: str) -> str:
        """
        Normalize a dialect-specific type to canonical form.
        
        Args:
            type_str: Type string like 'VARCHAR2(255)' or 'SERIAL'
        
        Returns:
            Normalized type string like 'VARCHAR(255)' or 'INTEGER'
        """
        pass
    
    @abstractmethod
    def is_auto_increment(self, col_def: str) -> bool:
        """
        Detect if a column definition includes auto-increment.
        
        Args:
            col_def: Full column definition string
        
        Returns:
            True if column is auto-increment, False otherwise
        """
        pass
    
    @staticmethod
    def for_dialect(dialect: str) -> DialectAdapter:
        """
        Factory method to get adapter for the specified dialect.
        
        Args:
            dialect: Dialect name ('oracle', 'postgres', 'mysql', 'sqlite')
        
        Returns:
            DialectAdapter instance for the dialect
        
        Raises:
            ValueError: If dialect is not supported
        """
        dialect_lower = dialect.lower()
        adapters = {
            'oracle': OracleAdapter(),
            'postgres': PostgresAdapter(),
            'postgresql': PostgresAdapter(),  # Alias
            'mysql': MySQLAdapter(),
            'sqlite': SQLiteAdapter(),
        }
        
        if dialect_lower not in adapters:
            supported = ', '.join(sorted(set(adapters.keys())))
            raise ValueError(
                f"Unsupported dialect: {dialect}. "
                f"Supported dialects: {supported}"
            )
        
        return adapters[dialect_lower]


class OracleAdapter(DialectAdapter):
    """Oracle dialect adapter (default)."""
    
    def __init__(self):
        self.name = 'oracle'
    
    type_map = {
        'VARCHAR2': 'VARCHAR',
        'NUMBER': 'NUMERIC',
        'NVARCHAR2': 'NVARCHAR',
        'NCHAR': 'NCHAR',
        'LONG': 'TEXT',
        'RAW': 'BINARY',
    }
    
    def normalize_type(self, type_str: str) -> str:
        """
        Normalize Oracle types to canonical form.
        
        Examples:
            'VARCHAR2(255)' → 'VARCHAR(255)'
            'NUMBER(10,2)' → 'NUMERIC(10,2)'
            'NUMBER' → 'NUMERIC'
        """
        # Extract base type (e.g., 'VARCHAR2' from 'VARCHAR2(255)')
        match = re.match(r'^([A-Z][A-Z0-9_]*)', type_str.upper())
        if not match:
            return type_str
        
        base_type = match.group(1)
        normalized = self.type_map.get(base_type, base_type)
        
        # Preserve precision/scale if present
        rest_match = re.search(r'(\(.*\))', type_str, re.IGNORECASE)
        if rest_match:
            normalized += rest_match.group(1)
        
        return normalized
    
    def is_auto_increment(self, col_def: str) -> bool:
        """
        Oracle uses GENERATED BY DEFAULT AS IDENTITY or GENERATED ALWAYS AS IDENTITY.
        
        Example: 'id NUMBER GENERATED BY DEFAULT AS IDENTITY'
        """
        upper = col_def.upper()
        return 'GENERATED' in upper and 'IDENTITY' in upper


class PostgresAdapter(DialectAdapter):
    """PostgreSQL dialect adapter."""
    
    def __init__(self):
        self.name = 'postgres'
    
    type_map = {
        'SERIAL': 'INTEGER',
        'BIGSERIAL': 'BIGINT',
        'SMALLSERIAL': 'SMALLINT',
        'TEXT': 'VARCHAR',
        'BYTEA': 'BINARY',
        'BOOL': 'BOOLEAN',
        'INT': 'INTEGER',
        'INT2': 'SMALLINT',
        'INT4': 'INTEGER',
        'INT8': 'BIGINT',
        'FLOAT4': 'REAL',
        'FLOAT8': 'DOUBLE PRECISION',
    }
    
    def normalize_type(self, type_str: str) -> str:
        """
        Normalize Postgres types to canonical form.
        
        Examples:
            'SERIAL' → 'INTEGER'
            'BIGSERIAL' → 'BIGINT'
            'TEXT' → 'VARCHAR'
            'VARCHAR(255)' → 'VARCHAR(255)' (unchanged)
        """
        # Extract base type
        match = re.match(r'^([A-Z][A-Z0-9_]*)', type_str.upper())
        if not match:
            return type_str
        
        base_type = match.group(1)
        normalized = self.type_map.get(base_type, base_type)
        
        # Preserve precision/scale if present (but not for SERIAL types)
        if base_type not in ('SERIAL', 'BIGSERIAL', 'SMALLSERIAL'):
            rest_match = re.search(r'(\(.*\))', type_str, re.IGNORECASE)
            if rest_match:
                normalized += rest_match.group(1)
        
        return normalized
    
    def is_auto_increment(self, col_def: str) -> bool:
        """
        Postgres uses SERIAL, BIGSERIAL, SMALLSERIAL, or GENERATED ALWAYS AS IDENTITY.
        
        Examples:
            'id SERIAL PRIMARY KEY'
            'id BIGSERIAL'
            'id INTEGER GENERATED ALWAYS AS IDENTITY'
        """
        upper = col_def.upper()
        return (
            'SERIAL' in upper or
            ('GENERATED' in upper and 'IDENTITY' in upper)
        )


class MySQLAdapter(DialectAdapter):
    """MySQL dialect adapter."""
    
    def __init__(self):
        self.name = 'mysql'
    
    type_map = {
        'TINYINT': 'SMALLINT',
        'MEDIUMINT': 'INTEGER',
        'INT': 'INTEGER',
        'BIGINT': 'BIGINT',
        'DATETIME': 'TIMESTAMP',
        'TINYTEXT': 'VARCHAR',
        'MEDIUMTEXT': 'TEXT',
        'LONGTEXT': 'TEXT',
        'TINYBLOB': 'BINARY',
        'MEDIUMBLOB': 'BINARY',
        'LONGBLOB': 'BINARY',
        'DOUBLE': 'DOUBLE PRECISION',
    }
    
    def normalize_type(self, type_str: str) -> str:
        """
        Normalize MySQL types to canonical form.
        
        Examples:
            'TINYINT(1)' → 'SMALLINT(1)'
            'DATETIME' → 'TIMESTAMP'
            'INT AUTO_INCREMENT' → 'INTEGER' (AUTO_INCREMENT handled separately)
        """
        # Extract base type
        match = re.match(r'^([A-Z][A-Z0-9_]*)', type_str.upper())
        if not match:
            return type_str
        
        base_type = match.group(1)
        normalized = self.type_map.get(base_type, base_type)
        
        # Preserve precision/scale if present
        rest_match = re.search(r'(\(.*\))', type_str, re.IGNORECASE)
        if rest_match:
            normalized += rest_match.group(1)
        
        return normalized
    
    def is_auto_increment(self, col_def: str) -> bool:
        """
        MySQL uses AUTO_INCREMENT keyword.
        
        Example: 'id INT AUTO_INCREMENT PRIMARY KEY'
        """
        return 'AUTO_INCREMENT' in col_def.upper()


class SQLiteAdapter(DialectAdapter):
    """SQLite dialect adapter."""
    
    def __init__(self):
        self.name = 'sqlite'
    
    type_map = {
        'TEXT': 'VARCHAR',
        'REAL': 'FLOAT',
        'BLOB': 'BINARY',
        'INT': 'INTEGER',
    }
    
    def normalize_type(self, type_str: str) -> str:
        """
        Normalize SQLite types to canonical form.
        
        Examples:
            'TEXT' → 'VARCHAR'
            'REAL' → 'FLOAT'
            'INTEGER' → 'INTEGER' (unchanged)
        
        Note: SQLite is extremely permissive with types and mostly ignores them.
        """
        # Extract base type
        match = re.match(r'^([A-Z][A-Z0-9_]*)', type_str.upper())
        if not match:
            return type_str
        
        base_type = match.group(1)
        normalized = self.type_map.get(base_type, base_type)
        
        # SQLite rarely uses precision/scale, but preserve if present
        rest_match = re.search(r'(\(.*\))', type_str, re.IGNORECASE)
        if rest_match:
            normalized += rest_match.group(1)
        
        return normalized
    
    def is_auto_increment(self, col_def: str) -> bool:
        """
        SQLite uses INTEGER PRIMARY KEY AUTOINCREMENT.
        
        Example: 'id INTEGER PRIMARY KEY AUTOINCREMENT'
        
        Note: In SQLite, 'INTEGER PRIMARY KEY' alone is auto-incrementing,
        but AUTOINCREMENT adds extra constraints.
        """
        upper = col_def.upper()
        return (
            'INTEGER' in upper and
            'PRIMARY KEY' in upper and
            'AUTOINCREMENT' in upper
        )
