# generated by datamodel-codegen:
#   filename:  types.json
#   timestamp: 2026-05-29T20:15:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SqlfyCliResponseTypes(RootModel[Any]):
    root: Any = Field(
        ...,
        description='JSON shapes produced by the SQLfy CLI as command output. Every property name is the camelCase alias that Pydantic emits via model_dump_json(by_alias=True).',
        title='SQLfy CLI Response Types',
    )


class MigrationHistory(BaseModel):
    """
    One entry in a migration history list.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: str = Field(..., description='Migration version string.')
    description: str = Field(..., description='Human-readable description.')


class VectorChunk(BaseModel):
    """
    One chunk from sqlfy chunks --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str = Field(..., description='Unique chunk ID.')
    type: str = Field(..., description='Chunk type (table, etc.).')
    title: str = Field(..., description='Short title.')
    content: str = Field(..., description='Full text for embedding.')
    metadata: dict[str, Any] = Field(..., description='Arbitrary metadata.')
    hint: str = Field(..., description='RAG retrieval hint.')


class InsightSeverity(Enum):
    """
    Severity of a schema insight finding.
    """

    error = 'error'
    warning = 'warning'
    info = 'info'


class InsightFinding(BaseModel):
    """
    One finding from sqlfy insights --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str = Field(..., description='Rule code (e.g. ORPHAN_TABLE).')
    severity: InsightSeverity = Field(..., description='Severity level.')
    category: str = Field(..., description='Category grouping.')
    message: str = Field(..., description='Human-readable description.')
    detail: str | None = Field(None, description='Extended explanation.')
    fix: str | None = Field(None, description='Suggested SQL/action.')
    table: str | None = Field(None, description='Affected table name.')
    column: str | None = Field(None, description='Affected column name.')


class InsightsSummary(BaseModel):
    """
    Aggregated finding counts inside InsightsResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    errors: int = Field(..., description='Error count.')
    warnings: int = Field(..., description='Warning count.')
    infos: int = Field(..., description='Info count.')
    total: int = Field(..., description='Total count.')
    healthy: bool = Field(..., description='True when no errors/warnings.')


class Findings(BaseModel):
    """
    Findings grouped by severity.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    error: list[InsightFinding] = Field(..., description='Error findings.')
    warning: list[InsightFinding] = Field(..., description='Warning findings.')
    info: list[InsightFinding] = Field(..., description='Info findings.')


class InsightsResult(BaseModel):
    """
    Full response from sqlfy insights --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: str = Field(..., description='Schema version.')
    fingerprint: str = Field(..., description='State fingerprint.')
    summary: InsightsSummary = Field(..., description='Aggregated counts.')
    findings: Findings = Field(..., description='Findings grouped by severity.')


class HealthGrade(Enum):
    """
    Qualitative health grade.
    """

    excellent = 'excellent'
    good = 'good'
    warning = 'warning'
    critical = 'critical'


class Status(Enum):
    """
    safe | unsafe | irreversible.
    """

    safe = 'safe'
    unsafe = 'unsafe'
    irreversible = 'irreversible'


class HealthMigrationStatus(BaseModel):
    """
    Per-migration safety row inside HealthResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    filename: str = Field(..., description='Migration filename.')
    status: Status = Field(..., description='safe | unsafe | irreversible.')
    errors: int = Field(..., description='Error count.')
    warnings: int = Field(..., description='Warning count.')
    has_drop_table: bool = Field(
        ..., alias='hasDropTable', description='Contains DROP TABLE.'
    )
    has_drop_column: bool = Field(
        ..., alias='hasDropColumn', description='Contains DROP COLUMN.'
    )


class HealthScoreBreakdown(BaseModel):
    """
    Score component breakdown inside HealthScore.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    base: int = Field(..., description='Base score.')
    error_penalty: int = Field(
        ..., alias='errorPenalty', description='Error deduction.'
    )
    warning_penalty: int = Field(
        ..., alias='warningPenalty', description='Warning deduction.'
    )
    irreversible_penalty: int = Field(
        ..., alias='irreversiblePenalty', description='Irreversible deduction.'
    )


class HealthScore(BaseModel):
    """
    Health score inside HealthResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    score: int = Field(..., description='Score 0-100.')
    grade: HealthGrade = Field(..., description='Qualitative grade.')
    breakdown: HealthScoreBreakdown = Field(..., description='Per-factor breakdown.')


class HealthSummary(BaseModel):
    """
    Migration folder stats inside HealthResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    total_migrations: int = Field(
        ..., alias='totalMigrations', description='Total count.'
    )
    safe_migrations: int = Field(..., alias='safeMigrations', description='Safe count.')
    unsafe_migrations: int = Field(
        ..., alias='unsafeMigrations', description='Unsafe count.'
    )
    irreversible_migrations: int = Field(
        ..., alias='irreversibleMigrations', description='Irreversible count.'
    )
    safe_percentage: int = Field(
        ..., alias='safePercentage', description='Percent safe 0-100.'
    )


class HealthFindings(BaseModel):
    """
    Aggregated finding counts inside HealthResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    errors: int = Field(..., description='Total error count.')
    warnings: int = Field(..., description='Total warning count.')
    infos: int = Field(..., description='Total info count.')
    by_code: dict[str, int] = Field(
        ..., alias='byCode', description='Counts by rule code.'
    )


class HealthResult(BaseModel):
    """
    Full response from sqlfy health --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    folder: str = Field(..., description='Migrations folder path.')
    timestamp: str = Field(..., description='ISO-8601 report timestamp.')
    summary: HealthSummary = Field(..., description='Migration stats.')
    findings: HealthFindings = Field(..., description='Finding counts.')
    migrations: list[HealthMigrationStatus] = Field(
        ..., description='Per-migration rows.'
    )
    health_score: HealthScore = Field(
        ..., alias='healthScore', description='Health score.'
    )
    recommendation: str = Field(..., description='Human-readable recommendation.')


class DiffStats(BaseModel):
    """
    Change count summary inside DiffResult and SimulateResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    tables_added: int = Field(..., alias='tablesAdded', description='Tables added.')
    tables_removed: int = Field(
        ..., alias='tablesRemoved', description='Tables removed.'
    )
    tables_modified: int = Field(
        ..., alias='tablesModified', description='Tables modified.'
    )
    columns_added: int = Field(..., alias='columnsAdded', description='Columns added.')
    columns_removed: int = Field(
        ..., alias='columnsRemoved', description='Columns removed.'
    )
    columns_modified: int = Field(
        ..., alias='columnsModified', description='Columns modified.'
    )
    sequences_added: int = Field(
        ..., alias='sequencesAdded', description='Sequences added.'
    )
    sequences_removed: int = Field(
        ..., alias='sequencesRemoved', description='Sequences removed.'
    )
    relationships_added: int = Field(
        ..., alias='relationshipsAdded', description='FK relationships added.'
    )
    relationships_removed: int = Field(
        ..., alias='relationshipsRemoved', description='FK relationships removed.'
    )
    is_breaking: bool = Field(
        ..., alias='isBreaking', description='Any breaking change.'
    )


class Change(Enum):
    """
    added | removed | modified.
    """

    added = 'added'
    removed = 'removed'
    modified = 'modified'


class DiffColumnChange(BaseModel):
    """
    Column-level change inside DiffTableChange.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str = Field(..., description='Column name.')
    change: Change = Field(..., description='added | removed | modified.')
    before: dict[str, Any] | None = Field(
        None, description='Column state before (absent for added).'
    )
    after: dict[str, Any] | None = Field(
        None, description='Column state after (absent for removed).'
    )
    diffs: list[str] | None = Field(None, description='Field change descriptions.')
    breaking: bool = Field(..., description='Could break existing code.')


class Change1(Enum):
    """
    added | removed.
    """

    added = 'added'
    removed = 'removed'


class DiffConstraintChange(BaseModel):
    """
    Constraint-level change inside DiffTableChange.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str | None = Field(..., description='Constraint name. Null if unnamed.')
    change: Change1 = Field(..., description='added | removed.')
    type: str = Field(..., description='Constraint kind.')
    columns: list[str] = Field(..., description='Columns in the constraint.')


class DiffIndexChange(BaseModel):
    """
    Index-level change inside DiffTableChange.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str = Field(..., description='Index name.')
    change: Change1 = Field(..., description='added | removed.')
    columns: list[str] = Field(..., description='Columns in the index.')
    unique: bool = Field(..., description='Whether unique.')


class DiffTableChange(BaseModel):
    """
    Table-level change inside DiffResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    full_name: str = Field(
        ..., alias='fullName', description='Fully-qualified table name.'
    )
    change: Change = Field(..., description='added | removed | modified.')
    breaking: bool = Field(..., description='Is this change breaking.')
    column_changes: list[DiffColumnChange] | None = Field(
        None, alias='columnChanges', description='Column changes.'
    )
    constraint_changes: list[DiffConstraintChange] | None = Field(
        None, alias='constraintChanges', description='Constraint changes.'
    )
    index_changes: list[DiffIndexChange] | None = Field(
        None, alias='indexChanges', description='Index changes.'
    )


class DiffSequenceChange(BaseModel):
    """
    Sequence-level change inside DiffResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    full_name: str = Field(
        ..., alias='fullName', description='Fully-qualified sequence name.'
    )
    change: Change = Field(..., description='added | removed | modified.')
    diffs: list[str] | None = Field(None, description='Field change descriptions.')


class DiffRelationshipChange(BaseModel):
    """
    FK relationship change inside DiffResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    change: Change1 = Field(..., description='added | removed.')
    from_: str = Field(..., alias='from', description='Source table name.')
    from_cols: list[str] = Field(
        ..., alias='fromCols', description='Source column names.'
    )
    to: str = Field(..., description='Target table name.')
    to_cols: list[str] = Field(..., alias='toCols', description='Target column names.')
    on_delete: str | None = Field(
        ..., alias='onDelete', description='ON DELETE action. Null if none.'
    )


class DiffResult(BaseModel):
    """
    Full response from sqlfy diff-versions --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version_a: str = Field(..., alias='versionA', description='Source version.')
    version_b: str = Field(..., alias='versionB', description='Target version.')
    fingerprint_a: str = Field(
        ..., alias='fingerprintA', description='Source SHA-256 fingerprint.'
    )
    fingerprint_b: str = Field(
        ..., alias='fingerprintB', description='Target SHA-256 fingerprint.'
    )
    stats: DiffStats = Field(..., description='Change counts.')
    table_changes: list[DiffTableChange] = Field(
        ..., alias='tableChanges', description='Table changes.'
    )
    sequence_changes: list[DiffSequenceChange] = Field(
        ..., alias='sequenceChanges', description='Sequence changes.'
    )
    relationship_changes: list[DiffRelationshipChange] = Field(
        ..., alias='relationshipChanges', description='FK changes.'
    )


class SimulateHealth(BaseModel):
    """
    Health snapshot nested inside SimulateResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    score: int = Field(..., description='Score 0-100.')
    grade: HealthGrade = Field(..., description='Qualitative grade.')
    errors: int = Field(..., description='Error insight count.')
    warnings: int = Field(..., description='Warning insight count.')


class SimulateDiff(BaseModel):
    """
    Diff section nested inside SimulateResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    stats: DiffStats = Field(..., description='Change counts.')
    is_breaking: bool = Field(
        ..., alias='isBreaking', description='Any breaking change.'
    )


class SimulateResult(BaseModel):
    """
    Full response from sqlfy simulate --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    timestamp: str = Field(..., description='ISO-8601 simulation timestamp.')
    base_version: str = Field(
        ..., alias='baseVersion', description='Base migration version.'
    )
    sql: str = Field(..., description='The simulated DDL.')
    success: bool = Field(..., description='Applied without parse errors.')
    is_safe: bool = Field(..., alias='isSafe', description='No destructive operations.')
    is_breaking: bool = Field(
        ..., alias='isBreaking', description='At least one breaking change detected.'
    )
    errors: list[str] = Field(..., description='Parse/validation errors.')
    warnings: list[str] = Field(..., description='Advisory warnings.')
    diff: SimulateDiff = Field(..., description='Structural diff.')
    health: SimulateHealth = Field(..., description='Health snapshot.')


class ImpactResult(BaseModel):
    """
    Full response from sqlfy impact --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    object_id: str = Field(..., alias='objectId', description='Analyzed schema object.')
    direct: list[str] = Field(..., description='Directly affected objects (depth 1).')
    transitive: list[str] = Field(
        ..., description='Transitively affected objects (depth > 1).'
    )
    depth_map: dict[str, int] = Field(
        ..., alias='depthMap', description='Object ID to traversal depth.'
    )
    by_type: dict[str, list[str]] = Field(
        ..., alias='byType', description='Affected objects grouped by type.'
    )
    critical_paths: list[list[str]] = Field(
        ..., alias='criticalPaths', description='Critical paths from source to leaves.'
    )
    max_depth: int = Field(
        ..., alias='maxDepth', description='Maximum traversal depth reached.'
    )
    total_count: int = Field(
        ..., alias='totalCount', description='Total affected count excluding source.'
    )


class Feasibility(Enum):
    """
    reversible | partial | irreversible.
    """

    reversible = 'reversible'
    partial = 'partial'
    irreversible = 'irreversible'


class RollbackAnalysis(BaseModel):
    """
    Rollback feasibility for one migration inside RollbackResult.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    migration: str = Field(..., description='Migration filename.')
    feasibility: Feasibility = Field(
        ..., description='reversible | partial | irreversible.'
    )
    score: int = Field(..., description='Rollback difficulty score 0-100.')
    rollback_script: str | None = Field(
        ...,
        alias='rollbackScript',
        description='Suggested rollback SQL. Null if irreversible.',
    )
    warnings: list[str] = Field(..., description='Risk warnings.')
    recommendations: list[str] = Field(..., description='Actionable recommendations.')
    operations: list[str] = Field(..., description='Detected SQL operations.')


class Summary(BaseModel):
    """
    Counts by feasibility.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    total: int = Field(..., description='Total migrations.')
    reversible: int = Field(..., description='Reversible count.')
    partial: int = Field(..., description='Partial count.')
    irreversible: int = Field(..., description='Irreversible count.')


class RollbackResult(BaseModel):
    """
    Full response from sqlfy rollback-analysis --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    summary: Summary = Field(..., description='Counts by feasibility.')
    migrations: list[RollbackAnalysis] = Field(
        ..., description='Per-migration analyses.'
    )


class SchemaManifest(BaseModel):
    """
    High-level metadata from sqlfy manifest.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: str = Field(
        ..., alias='schemaVersion', description='Latest migration version.'
    )
    fingerprint: str = Field(..., description='SHA-256 fingerprint.')
    dialect: str = Field(..., description='SQL dialect.')
    generated_at: str = Field(
        ..., alias='generatedAt', description='ISO-8601 timestamp.'
    )
    sqlfy_version: str = Field(
        ..., alias='sqlfyVersion', description='sqlfy tool version.'
    )
    node_count: int = Field(..., alias='nodeCount', description='Graph node count.')
    edge_count: int = Field(..., alias='edgeCount', description='Graph edge count.')
    table_count: int = Field(..., alias='tableCount', description='Table count.')
    column_count: int = Field(..., alias='columnCount', description='Column count.')
    sequence_count: int = Field(
        ..., alias='sequenceCount', description='Sequence count.'
    )
    relationship_count: int = Field(
        ..., alias='relationshipCount', description='FK relationship count.'
    )
    index_count: int = Field(..., alias='indexCount', description='Index count.')
    tables_without_pk: int = Field(
        ..., alias='tablesWithoutPk', description='Tables without primary key.'
    )
    migration_count: int = Field(
        ..., alias='migrationCount', description='Migration file count.'
    )
    migration_history: list[MigrationHistory] = Field(
        ..., alias='migrationHistory', description='Ordered migration list.'
    )


class ColumnState(BaseModel):
    """
    Column inside TableState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str = Field(..., description='Column name.')
    data_type: str = Field(
        ..., alias='dataType', description='Rendered type e.g. NUMBER(10,2).'
    )
    raw_type: str = Field(
        ..., alias='rawType', description='Base type name e.g. NUMBER.'
    )
    precision: int | None = Field(..., description='Numeric precision. Null if N/A.')
    scale: int | None = Field(..., description='Numeric scale. Null if N/A.')
    nullable: bool = Field(..., description='Accepts NULL.')
    default: str | None = Field(..., description='Default expression. Null if none.')
    is_pk: bool = Field(..., alias='isPk', description='Part of primary key.')
    is_fk: bool = Field(..., alias='isFk', description='Part of foreign key.')
    is_unique: bool = Field(..., alias='isUnique', description='Has unique constraint.')
    comment: str | None = Field(..., description='Column comment. Null if none.')


class ConstraintState(BaseModel):
    """
    Constraint inside TableState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str | None = Field(..., description='Name. Null if unnamed.')
    type: str = Field(..., description='primary_key|unique|foreign_key|check.')
    columns: list[str] = Field(..., description='Column names.')
    ref_table: str | None = Field(
        None, alias='refTable', description='Referenced table (FK only).'
    )
    ref_columns: list[str] | None = Field(
        None, alias='refColumns', description='Referenced columns (FK only).'
    )
    on_delete: str | None = Field(
        None, alias='onDelete', description='ON DELETE action (FK only).'
    )
    check_expr: str | None = Field(
        None, alias='checkExpr', description='CHECK expression (CHECK only).'
    )


class IndexState(BaseModel):
    """
    Index inside TableState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: str = Field(..., description='Index name.')
    columns: list[str] = Field(..., description='Columns in the index.')
    unique: bool = Field(..., description='Whether unique.')
    created_in: str = Field(
        ..., alias='createdIn', description='Created in migration ver.'
    )


class TableState(BaseModel):
    """
    Table inside SchemaState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_: str | None = Field(
        ..., alias='schema', description='Schema/owner. Null for default.'
    )
    name: str = Field(..., description='Table name (uppercased).')
    full_name: str = Field(..., alias='fullName', description='Fully-qualified name.')
    columns: list[ColumnState] = Field(..., description='Ordered columns.')
    constraints: list[ConstraintState] = Field(..., description='Constraints.')
    indexes: list[IndexState] = Field(..., description='Indexes.')
    comment: str | None = Field(..., description='Table comment.')
    created_in: str = Field(
        ..., alias='createdIn', description='Created in migration ver.'
    )
    modified_in: list[str] = Field(
        ..., alias='modifiedIn', description='Modified in migration versions.'
    )
    column_count: int = Field(
        ..., alias='columnCount', description='Number of columns.'
    )
    has_pk: bool = Field(..., alias='hasPk', description='Has a primary key.')
    pk_columns: list[str] = Field(
        ..., alias='pkColumns', description='PK column names.'
    )


class SequenceState(BaseModel):
    """
    Sequence inside SchemaState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_: str | None = Field(
        ..., alias='schema', description='Schema/owner. Null for default.'
    )
    name: str = Field(..., description='Sequence name.')
    full_name: str = Field(..., alias='fullName', description='Fully-qualified name.')
    start_with: int = Field(..., alias='startWith', description='START WITH value.')
    increment_by: int = Field(
        ..., alias='incrementBy', description='INCREMENT BY value.'
    )
    created_in: str = Field(
        ..., alias='createdIn', description='Created in migration ver.'
    )


class RelationshipState(BaseModel):
    """
    FK relationship inside SchemaState (from sqlfy dump).
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str = Field(..., description='Unique relationship ID.')
    from_table: str = Field(..., alias='fromTable', description='Source table.')
    from_columns: list[str] = Field(
        ..., alias='fromColumns', description='Source columns.'
    )
    to_table: str = Field(..., alias='toTable', description='Target table.')
    to_columns: list[str] = Field(..., alias='toColumns', description='Target columns.')
    constraint_name: str | None = Field(
        ..., alias='constraintName', description='FK name. Null if unnamed.'
    )
    on_delete: str | None = Field(
        ..., alias='onDelete', description='ON DELETE action. Null if none.'
    )
    cardinality: str = Field(..., description='many_to_one | one_to_one | unknown.')


class SchemaState(BaseModel):
    """
    Full response from sqlfy dump --format json.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version: str = Field(..., description='Latest migration version.')
    generated_at: str = Field(
        ..., alias='generatedAt', description='ISO-8601 generation timestamp.'
    )
    fingerprint: str = Field(..., description='SHA-256 fingerprint.')
    dialect: str = Field(..., description='SQL dialect.')
    tables: dict[str, TableState] = Field(..., description='Tables keyed by full name.')
    sequences: dict[str, SequenceState] = Field(
        ..., description='Sequences keyed by full name.'
    )
    relationships: list[RelationshipState] = Field(
        ..., description='All FK relationships.'
    )
    migration_history: list[MigrationHistory] = Field(
        ..., alias='migrationHistory', description='Ordered migration list.'
    )
    stats: dict[str, int] = Field(..., description='Summary counts.')
