"""
Tests for dialect adapters and multi-dialect support.

Tests type normalization and auto-increment detection across:
- Oracle (default)
- PostgreSQL  
- MySQL
- SQLite
"""

import pytest
from sqlfy.dialects import (
    DialectAdapter,
    OracleAdapter,
    PostgresAdapter,
    MySQLAdapter,
    SQLiteAdapter,
)


class TestDialectFactory:
    """Test DialectAdapter.for_dialect() factory method."""
    
    def test_oracle_dialect(self):
        adapter = DialectAdapter.for_dialect('oracle')
        assert isinstance(adapter, OracleAdapter)
        assert adapter.name == 'oracle'
    
    def test_postgres_dialect(self):
        adapter = DialectAdapter.for_dialect('postgres')
        assert isinstance(adapter, PostgresAdapter)
        assert adapter.name == 'postgres'
    
    def test_postgresql_alias(self):
        adapter = DialectAdapter.for_dialect('postgresql')
        assert isinstance(adapter, PostgresAdapter)
    
    def test_mysql_dialect(self):
        adapter = DialectAdapter.for_dialect('mysql')
        assert isinstance(adapter, MySQLAdapter)
        assert adapter.name == 'mysql'
    
    def test_sqlite_dialect(self):
        adapter = DialectAdapter.for_dialect('sqlite')
        assert isinstance(adapter, SQLiteAdapter)
        assert adapter.name == 'sqlite'
    
    def test_unsupported_dialect(self):
        with pytest.raises(ValueError, match='Unsupported dialect'):
            DialectAdapter.for_dialect('mssql')
    
    def test_case_insensitive(self):
        adapter = DialectAdapter.for_dialect('POSTGRES')
        assert isinstance(adapter, PostgresAdapter)


class TestOracleAdapter:
    """Test Oracle dialect adapter."""
    
    def test_normalize_varchar2(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('VARCHAR2(255)') == 'VARCHAR(255)'
    
    def test_normalize_number(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('NUMBER') == 'NUMERIC'
        assert adapter.normalize_type('NUMBER(10)') == 'NUMERIC(10)'
        assert adapter.normalize_type('NUMBER(10,2)') == 'NUMERIC(10,2)'
    
    def test_normalize_nvarchar2(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('NVARCHAR2(100)') == 'NVARCHAR(100)'
    
    def test_normalize_long(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('LONG') == 'TEXT'
    
    def test_normalize_raw(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('RAW(16)') == 'BINARY(16)'
    
    def test_normalize_unchanged(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('INTEGER') == 'INTEGER'
        assert adapter.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
    
    def test_is_auto_increment(self):
        adapter = OracleAdapter()
        assert adapter.is_auto_increment('id NUMBER GENERATED BY DEFAULT AS IDENTITY')
        assert adapter.is_auto_increment('id NUMBER GENERATED ALWAYS AS IDENTITY')
        assert not adapter.is_auto_increment('id NUMBER')
        assert not adapter.is_auto_increment('id NUMBER PRIMARY KEY')


class TestPostgresAdapter:
    """Test PostgreSQL dialect adapter."""
    
    def test_normalize_serial(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('SERIAL') == 'INTEGER'
        assert adapter.normalize_type('BIGSERIAL') == 'BIGINT'
        assert adapter.normalize_type('SMALLSERIAL') == 'SMALLINT'
    
    def test_normalize_text(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('TEXT') == 'VARCHAR'
    
    def test_normalize_bytea(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('BYTEA') == 'BINARY'
    
    def test_normalize_bool(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('BOOL') == 'BOOLEAN'
    
    def test_normalize_int_aliases(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('INT') == 'INTEGER'
        assert adapter.normalize_type('INT2') == 'SMALLINT'
        assert adapter.normalize_type('INT4') == 'INTEGER'
        assert adapter.normalize_type('INT8') == 'BIGINT'
    
    def test_normalize_float_aliases(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('FLOAT4') == 'REAL'
        assert adapter.normalize_type('FLOAT8') == 'DOUBLE PRECISION'
    
    def test_normalize_varchar_preserved(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
    
    def test_is_auto_increment(self):
        adapter = PostgresAdapter()
        assert adapter.is_auto_increment('id SERIAL PRIMARY KEY')
        assert adapter.is_auto_increment('id BIGSERIAL')
        assert adapter.is_auto_increment('id INTEGER GENERATED ALWAYS AS IDENTITY')
        assert not adapter.is_auto_increment('id INTEGER')
        assert not adapter.is_auto_increment('id INTEGER PRIMARY KEY')


class TestMySQLAdapter:
    """Test MySQL dialect adapter."""
    
    def test_normalize_tinyint(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('TINYINT') == 'SMALLINT'
        assert adapter.normalize_type('TINYINT(1)') == 'SMALLINT(1)'
    
    def test_normalize_mediumint(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('MEDIUMINT') == 'INTEGER'
    
    def test_normalize_int(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('INT') == 'INTEGER'
    
    def test_normalize_datetime(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('DATETIME') == 'TIMESTAMP'
    
    def test_normalize_text_types(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('TINYTEXT') == 'VARCHAR'
        assert adapter.normalize_type('MEDIUMTEXT') == 'TEXT'
        assert adapter.normalize_type('LONGTEXT') == 'TEXT'
    
    def test_normalize_blob_types(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('TINYBLOB') == 'BINARY'
        assert adapter.normalize_type('MEDIUMBLOB') == 'BINARY'
        assert adapter.normalize_type('LONGBLOB') == 'BINARY'
    
    def test_normalize_double(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('DOUBLE') == 'DOUBLE PRECISION'
    
    def test_is_auto_increment(self):
        adapter = MySQLAdapter()
        assert adapter.is_auto_increment('id INT AUTO_INCREMENT PRIMARY KEY')
        assert adapter.is_auto_increment('id BIGINT AUTO_INCREMENT')
        assert not adapter.is_auto_increment('id INT')
        assert not adapter.is_auto_increment('id INT PRIMARY KEY')


class TestSQLiteAdapter:
    """Test SQLite dialect adapter."""
    
    def test_normalize_text(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('TEXT') == 'VARCHAR'
    
    def test_normalize_real(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('REAL') == 'FLOAT'
    
    def test_normalize_blob(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('BLOB') == 'BINARY'
    
    def test_normalize_int(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('INT') == 'INTEGER'
    
    def test_normalize_integer_unchanged(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('INTEGER') == 'INTEGER'
    
    def test_is_auto_increment(self):
        adapter = SQLiteAdapter()
        assert adapter.is_auto_increment('id INTEGER PRIMARY KEY AUTOINCREMENT')
        # Note: SQLite's INTEGER PRIMARY KEY alone is auto-incrementing,
        # but the adapter specifically checks for AUTOINCREMENT keyword
        assert not adapter.is_auto_increment('id INTEGER PRIMARY KEY')
        assert not adapter.is_auto_increment('id INTEGER')


class TestTypeNormalizationConsistency:
    """Test that type normalization is consistent across dialects."""
    
    def test_varchar_preserved(self):
        """VARCHAR should be preserved across all dialects."""
        oracle = OracleAdapter()
        postgres = PostgresAdapter()
        mysql = MySQLAdapter()
        sqlite = SQLiteAdapter()
        
        assert oracle.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
        assert postgres.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
        assert mysql.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
        assert sqlite.normalize_type('VARCHAR(255)') == 'VARCHAR(255)'
    
    def test_integer_preserved(self):
        """INTEGER should be preserved across all dialects."""
        oracle = OracleAdapter()
        postgres = PostgresAdapter()
        mysql = MySQLAdapter()
        sqlite = SQLiteAdapter()
        
        assert oracle.normalize_type('INTEGER') == 'INTEGER'
        assert postgres.normalize_type('INTEGER') == 'INTEGER'
        assert mysql.normalize_type('INTEGER') == 'INTEGER'
        assert sqlite.normalize_type('INTEGER') == 'INTEGER'
    
    def test_numeric_canonical(self):
        """NUMERIC should be the canonical form for numeric types."""
        oracle = OracleAdapter()
        postgres = PostgresAdapter()
        
        assert oracle.normalize_type('NUMBER') == 'NUMERIC'
        # Postgres NUMERIC is already canonical
        assert postgres.normalize_type('NUMERIC') == 'NUMERIC'


class TestCaseInsensitivity:
    """Test that type normalization handles case variations."""
    
    def test_oracle_lowercase(self):
        adapter = OracleAdapter()
        assert adapter.normalize_type('varchar2(255)') == 'VARCHAR(255)'
        assert adapter.normalize_type('number') == 'NUMERIC'
    
    def test_postgres_lowercase(self):
        adapter = PostgresAdapter()
        assert adapter.normalize_type('serial') == 'INTEGER'
        assert adapter.normalize_type('text') == 'VARCHAR'
    
    def test_mysql_lowercase(self):
        adapter = MySQLAdapter()
        assert adapter.normalize_type('tinyint') == 'SMALLINT'
        assert adapter.normalize_type('datetime') == 'TIMESTAMP'
    
    def test_sqlite_lowercase(self):
        adapter = SQLiteAdapter()
        assert adapter.normalize_type('text') == 'VARCHAR'
        assert adapter.normalize_type('real') == 'FLOAT'


class TestEdgeCases:
    """Test edge cases and unusual type definitions."""
    
    def test_type_with_spaces_in_precision(self):
        """Test types with spaces in precision/scale."""
        oracle = OracleAdapter()
        # NUMBER ( 10 , 2 ) with spaces
        assert oracle.normalize_type('NUMBER(10, 2)') == 'NUMERIC(10, 2)'
        assert oracle.normalize_type('NUMBER( 10 , 2 )') == 'NUMERIC( 10 , 2 )'
    
    def test_unknown_type_preserved(self):
        """Unknown types should be preserved as-is."""
        oracle = OracleAdapter()
        assert oracle.normalize_type('CUSTOM_TYPE') == 'CUSTOM_TYPE'
    
    def test_empty_string(self):
        """Empty string should be returned as-is."""
        oracle = OracleAdapter()
        assert oracle.normalize_type('') == ''
    
    def test_type_without_base(self):
        """Type that doesn't match pattern should be returned as-is."""
        oracle = OracleAdapter()
        assert oracle.normalize_type('123') == '123'


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
